server:
  port: 8600
spring:
  application:
    name: ${service.name:cosid-example-jdbc}
cosid:
  enabled: true
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: jdbc
    guarder:
      enabled: true
  snowflake:
    enabled: true
    provider:
      short_id:
        converter:
          prefix: cosid_
          type: radix
          radix:
            char-size: 11
            pad-start: false
      order_item:
        sequence-bit: 12
      snowflake:
        sequence-bit: 12
      safeJs:
        sequence-bit: 9
  segment:
    enabled: true
    mode: chain
    distributor:
      type: jdbc
    share:
      offset: 0
      step: 100
      converter:
        prefix: cosid_
        type: radix
        radix:
          char-size: 6
          pad-start: false
    provider:
      order:
        offset: 10000
        step: 100
      longId:
        offset: 10000
        step: 100

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    me.ahoo.cosid: debug
