coverage:
  range: 60..100
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 1%
    project:
      default:
        target: 80%
        threshold: 1%
ignore:
  - "cosid-test/.*"
  - "examples/.*"
  - "cosid-benchmark/.*"
  - "cosid-proxy/.*"
  - "cosid-proxy-server/.*"
