server:
  port: 8600
spring:
  application:
    name: ${service.name:cosid-example-proxy}

#  cloud:
#    discovery:
#      client:
#        simple:
#          instances:
#            cosid-proxy:
#              - host: localhost
#                port: 8688
#              - host: localhost
#                port: 8788
cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: proxy
    guarder:
      enabled: true
  snowflake:
    enabled: true
  proxy:
    host: http://localhost:8688
#    host: lb://cosid-proxy

#  segment:
#    enabled: true
#    mode: chain
#    distributor:
#      type: proxy

logging:
  level:
    me.ahoo.cosid: debug
