server:
  port: 8008
spring:
  application:
    name: ${service.name:cosid-example}
  redis:
    url: redis://localhost:6379

cosid:
  namespace: ${spring.application.name}
  machine:
    enabled: true
    clock-backwards:
      spin-threshold: 10
      broken-threshold: 2000
      #      stable: true
      #      machine-bit: 10
      #      instance-id: ${HOSTNAME}
    distributor:
      type: redis
    #        manual:
    #          machine-id: 0
    state-storage:
      local:
        state-location: ./cosid-machine-state/
    guarder:
      enabled: true
  snowflake:
    enabled: true
    #    epoch: 1577203200000
    share:
      clock-sync: true
      friendly: true
    provider:
      short_id:
        converter:
          prefix: cosid_
          type: radix
          radix:
            char-size: 11
            pad-start: false
      order_item:
        sequence-bit: 12
      snowflake:
        sequence-bit: 12
      safeJs:
        machine-bit: 3
        sequence-bit: 9
  segment:
    enabled: true
    mode: chain
    chain:
      safe-distance: 5
      prefetch-worker:
        core-pool-size: 2
        prefetch-period: 1s
    distributor:
      type: redis
    share:
      offset: 0
      step: 100
    provider:
      order:
        offset: 10000
        step: 100
      longId:
        offset: 10000
        step: 100


mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mappers/*.xml

logging:
  level:
    me.ahoo.cosid: debug
