cosid:
  namespace: ${spring.application.name}
  snowflake:
    #    instance-id:
    #      stable: true
    #      machine-bit: 10
    #      instance-id: ${HOSTNAME}
    #  stateful-set:
    #    enabled: true
    #  manual:
    #    enabled: true
    #    machine-id: 1
    redis:
      enabled: true
    provider:
      order:
        #      epoch:
        #      timestamp-bit:
        sequence-bit: 12
      user:
        #      epoch:
        #      timestamp-bit:
        sequence-bit: 12
    enabled: true
  redis:
    enabled: false
    provider:
      order:
        step: 100
    share:
      step: 10
