cosid:
  namespace: ${spring.application.name}
  snowflake:
  #  stateful-set:
  #    enabled: true
  #  manual:
  #    enabled: true
  #    machine-id: 1
    redis:
      enabled: true
    providers:
      order:
  #      epoch:
  #      timestamp-bit:
  #      machine-bit:
        sequence-bit: 12
      user:
  #      epoch:
  #      timestamp-bit:
  #      machine-bit:
        sequence-bit: 12
    enabled: true
#    instance-id:
#      stable: true
#  redis:
#    enabled: true
#    providers:
#      order:
#        step: 100
