server:
  port: 8602
spring:
  application:
    name: ${service.name:cosid-example-zookeeper}
cosid:
  zookeeper:
    connect-string: localhost:2181
  namespace: ${spring.application.name}
  machine:
    enabled: true
    distributor:
      type: zookeeper
    guarder:
      enabled: true
  snowflake:
    enabled: true
#  segment:
#    enabled: true
#    mode: chain
#    distributor:
#      type: zookeeper

logging:
  level:
    me.ahoo.cosid: debug
