name: Codecov
on:
  pull_request:
    paths-ignore:
      - 'cosid-benchmark/**'
      - 'docs/**'
      - 'document/**'
      - 'documentation/**'
      - 'examples/**'
      - 'wiki/**'
env:
  CI: true
jobs:
  codecov:
    name: Codecov
    runs-on: ubuntu-latest
    env:
      MYSQL: 5.1
      CODECOV: true
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Start Mysql
        run: sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Init CosId-Db
        run: mysql -vvv -h localhost -uroot -proot < cosid-jdbc/src/main/init-script/init-cosid-mysql.sql

      - name: Build Code Coverage Report
        run: ./gradlew codeCoverageReport --stacktrace

      - name: Upload Code Coverage Report to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
#          directory: ./build/reports/jacoco/codeCoverageReport/
          files: ./code-coverage-report/build/reports/jacoco/codeCoverageReport/codeCoverageReport.xml
          path_to_write_report: ./coverage/codecov_report.txt
