#
# Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Example Test
on: [ push, pull_request ]
jobs:
  example-jdbc-test:
    name: CosId Example Test
    runs-on: ubuntu-latest
    env:
      MYSQL: 5.1
    steps:
      - name: Start Mysql
        run: sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Init CosId-Db
        run: mysql -vvv -h localhost -uroot -proot < cosid-jdbc/src/main/init-script/init-cosid-mysql.sql

      - name: Test Example-Jdbc
        run: gradle cosid-example-jdbc:clean cosid-example-jdbc:check

  example-redis-test:
    name: Example Redis Test
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test Example-Redis
        run: gradle cosid-example-redis:clean cosid-example-redis:check

  example-zookeeper-test:
    name: Example Zookeeper Test
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test Example-Zookeeper
        run: gradle cosid-example-zookeeper:clean cosid-example-zookeeper:check
        
  example-proxy-test:
    name: Example Proxy Test
    runs-on: ubuntu-latest
    services:
      zookeeper:
        image: zookeeper
        ports:
          - 2181:2181
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test Example-Proxy
        run: gradle cosid-example-proxy:clean cosid-example-proxy:check

