#
# Copyright [2021-present] [ahoo wang <ahoowang@qq.com> (https://github.com/Ahoo-Wang)].
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Integration Test
on:
  push:
    paths-ignore:
      - 'cosid-benchmark/**'
      - 'docs/**'
      - 'document/**'
      - 'documentation/**'
      - 'examples/**'
      - 'wiki/**'
  pull_request:
    paths-ignore:
      - 'cosid-benchmark/**'
      - 'docs/**'
      - 'document/**'
      - 'documentation/**'
      - 'examples/**'
      - 'wiki/**'
env:
  CI: true
jobs:
  cosid-core-test:
    name: CosId Core Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Core
        run: ./gradlew cosid-core:clean cosid-core:check

  cosid-jackson-test:
    name: CosId Jackson Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Jackson
        run: ./gradlew cosid-jackson:clean cosid-jackson:check

  cosid-axon-test:
    name: CosId Axon Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Axon
        run: ./gradlew cosid-axon:clean cosid-axon:check

  cosid-activiti-test:
    name: CosId Activiti Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Activiti
        run: ./gradlew cosid-activiti:clean cosid-activiti:check

  cosid-flowable-test:
    name: CosId Flowable Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Flowable
        run: ./gradlew cosid-flowable:clean cosid-flowable:check

  cosid-mybatis-test:
    name: CosId Mybatis Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Mybatis
        run: ./gradlew cosid-mybatis:clean cosid-mybatis:check

  cosid-spring-jdbc-test:
    name: CosId Spring Jdbc Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Spring-Jdbc
        run: ./gradlew cosid-spring-data-jdbc:clean cosid-spring-data-jdbc:check

  cosid-spring-redis-test:
    name: CosId Spring Redis Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Spring-Redis
        run: ./gradlew cosid-spring-redis:clean cosid-spring-redis:check

  cosid-mongo-test:
    name: CosId Mongo Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    env:
      CI: ''
    services:
      mongo:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        options: >-
          --health-cmd "mongo --eval \"printjson(db.serverStatus())\""
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Mongo
        run: ./gradlew cosid-mongo:clean cosid-mongo:check

  cosid-proxy-test:
    name: CosId Proxy Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Proxy
        run: ./gradlew cosid-proxy:clean cosid-proxy:check

  cosid-zookeeper-test:
    name: CosId Zookeeper Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Test CosId-Zookeeper
        run: ./gradlew cosid-zookeeper:clean cosid-zookeeper:check

  # https://github.com/actions/virtual-environments/issues/375
  # https://github.blog/changelog/2020-02-21-github-actions-breaking-change-ubuntu-virtual-environments-will-no-longer-start-the-mysql-service-automatically/
  cosid-jdbc-test:
    name: CosId Jdbc Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    env:
      MYSQL: 5.1
    steps:
      - name: Start Mysql
        run: sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Init CosId-Db
        run: mysql -vvv -h localhost -uroot -proot < cosid-jdbc/src/main/init-script/init-cosid-mysql.sql

      - name: Test CosId-Jdbc
        run: ./gradlew cosid-jdbc:clean cosid-jdbc:check

  cosid-spring-boot-starter-test:
    name: CosId Spring Boot Starter Test
    needs: [ cosid-core-test ]
    runs-on: ubuntu-latest
    steps:
      - name: Start Mysql
        run: sudo /etc/init.d/mysql start

      - name: Checkout
        uses: actions/checkout@master

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Init CosId-Db
        run: mysql -vvv -h localhost -uroot -proot < cosid-jdbc/src/main/init-script/init-cosid-mysql.sql

      - name: Test CosId-Spring-Boot-Starter
        run: ./gradlew cosid-spring-boot-starter:clean cosid-spring-boot-starter:check
